### ISSUE TITLE
[FEATURE]: Perplexity API Support

### ISSUE THREAD

**Issue by surapuramakhil** [feder-cr/LinkedIn_AIHawk_automatic_job_application#760]
### Feature summary

Support for Perplexity API's

### Feature description

Support for Perplexity API's for LLMS

**Comment by ldhiman** [comment]
I can help you in doing that

**Comment by surapuramakhil** [comment]
Sure updating this to you. 

Have a look at this PR this will help you 
https://github.com/AIHawk-app/Auto_Jobs_Applier/pull/757

**Comment by feder-cr** [comment]
@ldhiman very good

**Comment by ldhiman** [comment]
@surapuramakhil Close this issue

**Comment by surapuramakhil** [comment]
wait friend till I make release. till I merge into main 😅
